language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="https://w3c.github.io/hr-time/W3CTRMANIFEST"
  - DECISION="https://www.w3.org/2015/06/24-webperf-minutes.html#item01"
  - secure: "aSCngDOjj13BMsqFCrzs5QQNv5/S1WjEkidGIZfdDZtxHbSNfeqN0KY0lwbXE3pp09MYQwiBY13AYe6fXlvkxGYOg5EWAHEpxJlTNDpzk6mv1goLahbby4E8v+iF52s3HGuVfzCN+Uk2SM6T+X3+MIIb15PCRooiQwSPS8Uwuzs="
script:
- echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'
